name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - uses: joshjohanning/npm-version-check-action@v1

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run application
      run: npm run test | tee results.log

    - name: Strip ANSI codes and publish to job summary
      run: |
        echo '```' >> $GITHUB_STEP_SUMMARY
        # Strip ANSI escape sequences from the output
        sed 's/\x1b\[[0-9;]*m//g' results.log >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
