name: Publish Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      npm:
        description: 'Publish to NPM'
        type: boolean
        default: false
      gh:
        description: 'Publish to GitHub Packages'
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package tarball
        run: npm pack

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: '*.tgz'

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: '*.tgz'
          retention-days: 1

  publish_npm:
    needs: build
    if: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.npm) }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download tarball
        uses: actions/download-artifact@v6
        with:
          name: package

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: NPM publish
        run: npm publish *.tgz --provenance

  publish_gh:
    needs: build
    if: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.gh) }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Download tarball
        uses: actions/download-artifact@v6
        with:
          name: package

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'

      - name: GitHub Packages publish
        run: npm publish *.tgz --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
