name: Publish Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      npm:
        description: 'Publish to NPM'
        type: boolean
        default: false
      gh:
        description: 'Publish to GitHub Packages'
        type: boolean
        default: true

jobs:
  publish_npm:
    if: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.npm) }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: NPM publish
        run: npm publish --provenance --access public

  publish_gh:
    if: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.gh) }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: GitHub Packages publish
        run: npm publish --access public
